### ISSUE TITLE
Macht das Repo Privat bevor ihr raus geschmissen werdet :D

### ISSUE THREAD

**Issue by nikita68** [sharaku17/SystemPraktikumTeam9#1]

**Comment by nikita68** [comment]
BUMP

**Comment by sharaku17** [comment]
Hey danke für den Tipp, haben leider keinen Paid Acc um das Repo privat zu machen. 
Werd aber mit meinen Partner mal nach einer Alternative reden. Danke nochmals :)

**Comment by nikita68** [comment]
Ihr könnt über euer RWTH account einen kostenlosen pro account [bekommen](https://education.github.com/pack)

**Comment by sharaku17** [comment]
Danke!! hat geklappt :)
